modLoader="javafml"
loaderVersion="[24,]"
issueTrackerURL="https://github.com/Clownvin/Just-A-Few-More-Ores/issues"
displayURL="https://minecraft.curseforge.com/projects/just-a-few-more-ores"
logoFile="logo.png"

[[mods]]
    modId="jafmores"
    version="${file.jarVersion}"
    displayName="Just A Few More Ores"
    updateJSONURL="https://raw.githubusercontent.com/Clownvin/Just-A-Few-More-Ores/1.13.2/update.json"
    authors="Clownvin"
    credits="Clownvin, pixelgear_"
    description='''
    A simple mod that makes delving into Minecraft's depth worthwhile again by adding just a few more ores.
    '''